import {chromium} from '@playwright/test';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {validateTheme} from '../shared/theme-model.mjs';
const url=process.env.STUDIO_URL||'http://127.0.0.1:5190/studio/',browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url,{waitUntil:'networkidle'});
for(const text of ['新建任务','墨山主题验收','主题菜单','启用小行者','择景，不分发'])if(!await page.getByText(text,{exact:false}).count())throw Error('Missing preview surface: '+text);
if(await page.locator('.gallery-card').count()<4)throw Error('Official gallery is incomplete');await page.locator('[data-source="xbox-official"] button').click();if(!await page.locator('[data-source="xbox-official"]').evaluate(el=>el.classList.contains('selected')))throw Error('Gallery selection did not apply');
await page.locator('#backgroundMode').selectOption('local');const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9JfRgAAAAASUVORK5CYII=','base64');await page.locator('#localFile').setInputFiles({name:'mist.png',mimeType:'image/png',buffer:png});await page.locator('#position').selectOption('left center');await page.locator('#dim').fill('62');await page.locator('#art').fill('31');
const variables=await page.locator('#preview').evaluate(el=>({image:el.style.getPropertyValue('--studio-image'),position:el.style.getPropertyValue('--studio-position'),dim:el.style.getPropertyValue('--studio-dim'),intensity:el.style.getPropertyValue('--studio-intensity')}));if(!variables.image.includes('data:image/png')||variables.position!=='left center'||variables.dim!=='0.62'||variables.intensity!=='0.31')throw Error('Local background controls did not update preview');
await page.locator('#reducedMotion').check();if(!await page.locator('#preview').evaluate(el=>el.classList.contains('reduced-motion')))throw Error('Reduced motion did not apply');const wayfarer=page.locator('#wayfarer');if(await wayfarer.evaluate(el=>getComputedStyle(el).pointerEvents)!=='none'||await wayfarer.locator('em').textContent()!=='静候下一段行程')throw Error('Companion is not non-interactive with static status');
const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise,temp=path.join(os.tmpdir(),'wukong-forge-export.json');await download.saveAs(temp);validateTheme(JSON.parse(fs.readFileSync(temp,'utf8')));fs.rmSync(temp,{force:true});await page.locator('#preset').click();if(!await page.locator('#preview').evaluate(el=>el.classList.contains('high-read')))throw Error('High readability preset did not apply');await page.reload({waitUntil:'networkidle'});if(!await page.locator('#preview').evaluate(el=>el.classList.contains('high-read')))throw Error('Effective configuration did not persist locally');
await page.screenshot({path:'docs/screenshots/theme-studio.png',fullPage:true});if(!fs.existsSync('docs/screenshots/theme-studio.png')||errors.length)throw Error('Studio screenshot or console verification failed: '+errors.join(';'));await browser.close();console.log('Studio configuration, gallery, accessibility, companion, export, and screenshot PASS');
