import fs from 'node:fs';import http from 'node:http';import process from 'node:process';import {WebSocket} from 'ws';
const [,,mode,portRaw,themePath]=process.argv,port=Number(portRaw);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Port must be 1024..65535');
const request=p=>new Promise((resolve,reject)=>{const r=http.get({host:'127.0.0.1',port,path:p,timeout:2500},x=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>resolve(JSON.parse(d)))});r.on('error',reject);r.on('timeout',()=>r.destroy(Error('CDP timeout')))});
const version=await request('/json/version');if(!/^ws:\/\/127\.0\.0\.1(?::\d+)?\//.test(version.webSocketDebuggerUrl||''))throw Error('Refusing non-loopback CDP endpoint');
if(mode==='--verify'){console.log(JSON.stringify({ok:true,address:'127.0.0.1',browserId:version.id||null}));process.exit(0)}if(!['--apply','--restore'].includes(mode))throw Error('Use --verify|--apply|--restore <port> [theme.json]');
const css=mode==='--restore'?'':fs.readFileSync(new URL('./forge-theme.css',import.meta.url),'utf8'),theme=themePath?JSON.parse(fs.readFileSync(themePath,'utf8')):null,companion=theme?.companion?.enabled?{...theme.companion,image:'data:image/png;base64,'+fs.readFileSync(new URL('../assets/little-wayfarer.png',import.meta.url)).toString('base64')}:null;
const apply=`(()=>{let s=document.getElementById('wukong-forge-style');if(!s){s=document.createElement('style');s.id='wukong-forge-style';document.head.append(s)}s.textContent=${JSON.stringify(css)};document.documentElement.classList.add('forge-ink-mountain');[...document.querySelectorAll('button')].filter(b=>b.textContent.includes('新建任务')).forEach(b=>b.classList.add('forge-new-task'));const c=${JSON.stringify(companion)};let el=document.querySelector('.forge-wayfarer');if(!c){el?.remove();return}if(!el){el=document.createElement('div');el.className='forge-wayfarer';el.setAttribute('aria-hidden','true');document.body.append(el)}el.dataset.side=c.side;el.dataset.motion=c.motion==='still'?'still':'quiet';el.dataset.status='静候下一段行程';el.style.setProperty('--forge-companion-size',c.size+'px');el.innerHTML='<img alt="" src="'+c.image+'">'})()`;
const restore=`document.getElementById('wukong-forge-style')?.remove();document.querySelector('.forge-wayfarer')?.remove();document.documentElement.classList.remove('forge-ink-mountain')`;
for(const t of (await request('/json/list')).filter(t=>t.type==='page'&&(/^(app:|http:\/\/localhost)/.test(t.url))))await new Promise((resolve,reject)=>{const ws=new WebSocket(t.webSocketDebuggerUrl);ws.on('open',()=>ws.send(JSON.stringify({id:1,method:'Runtime.evaluate',params:{expression:mode==='--restore'?restore:apply}})));ws.on('message',()=>{ws.close();resolve()});ws.on('error',reject)});console.log(mode+' complete on loopback CDP');
