import {DEFAULT_THEME,makeTheme,validateTheme} from '../shared/theme-model.mjs';
const $=id=>document.getElementById(id),storage='wukong-codex-forge.theme.v1',clone=value=>JSON.parse(JSON.stringify(value));let localImage='',theme=loadTheme();
function loadTheme(){try{return makeTheme(JSON.parse(localStorage.getItem(storage)))}catch{return clone(DEFAULT_THEME)}}
function save(){localStorage.setItem(storage,JSON.stringify(theme))}
function status(message){$('status').textContent=message}
function render(){validateTheme(theme);$('themeName').value=theme.name;$('backgroundMode').value=theme.background.mode;$('position').value=theme.background.position;$('dim').value=Math.round(theme.background.dim*100);$('art').value=Math.round(theme.background.taskIntensity*100);$('dimOut').value=Math.round(theme.background.dim*100)+'%';$('artOut').value=Math.round(theme.background.taskIntensity*100)+'%';$('reducedMotion').checked=theme.accessibility.reducedMotion;$('companion').checked=theme.companion.enabled;$('side').value=theme.companion.side;$('size').value=theme.companion.size;$('sizeOut').value=theme.companion.size+'px';$('still').checked=theme.companion.motion==='still';$('localFileLabel').hidden=theme.background.mode!=='local';const preview=$('preview');preview.style.setProperty('--studio-dim',theme.background.dim);preview.style.setProperty('--studio-intensity',theme.background.taskIntensity);preview.style.setProperty('--studio-position',theme.background.position);preview.classList.toggle('high-read',theme.accessibility.preset==='high-read');preview.classList.toggle('reduced-motion',theme.accessibility.reducedMotion);const image=theme.background.mode==='local'&&localImage?'url("'+localImage.replaceAll('"','%22')+'")':'none';preview.style.setProperty('--studio-image',image);$('previewPreset').textContent=theme.accessibility.preset==='high-read'?'高可读性预设':'工作台预设';$('previewBackground').textContent=theme.background.mode==='local'&&localImage?'本地图片 · 已应用':theme.background.mode==='gallery'?'官方来源 · 需下载后导入':'纯墨 · 无背景';const wayfarer=$('wayfarer');wayfarer.hidden=!theme.companion.enabled;wayfarer.dataset.side=theme.companion.side;wayfarer.dataset.motion=theme.accessibility.reducedMotion||theme.companion.motion==='still'?'still':'quiet';wayfarer.style.setProperty('--companion-size',theme.companion.size+'px');document.querySelectorAll('.gallery-card').forEach(card=>card.classList.toggle('selected',card.dataset.source===theme.background.source));save()}
function update(mutator){mutator(theme);theme=makeTheme(theme);render()}
for(const [id,mutator] of [['themeName',v=>theme.name=v],['backgroundMode',v=>theme.background.mode=v],['position',v=>theme.background.position=v],['dim',v=>theme.background.dim=Number(v)/100],['art',v=>theme.background.taskIntensity=Number(v)/100],['reducedMotion',v=>theme.accessibility.reducedMotion=v],['companion',v=>theme.companion.enabled=v],['side',v=>theme.companion.side=v],['size',v=>theme.companion.size=Number(v)],['still',v=>theme.companion.motion=v?'still':'quiet']])$(id).addEventListener('input',e=>update(()=>mutator(e.target.type==='checkbox'?e.target.checked:e.target.value)));
$('localFile').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(file.size>16*1024*1024){status('图片超过 16 MB，未导入。');return}const reader=new FileReader;reader.onload=()=>{localImage=reader.result;update(()=>{theme.background.mode='local';theme.background.source=file.name;theme.background.asset=null});status('本地背景仅保存在当前 Studio 会话；导出后请用 theme.ps1 -Image 导入运行时。')};reader.readAsDataURL(file)});
$('themeImport').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader;reader.onload=()=>{try{theme=makeTheme(JSON.parse(reader.result));localImage='';render();status('有效主题已导入。若它引用本地背景，请重新选择图片。')}catch(error){status('拒绝主题：'+error.message)}};reader.readAsText(file,'utf-8')});
document.querySelectorAll('.gallery-card button').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.gallery-card');update(()=>{theme.background.mode='gallery';theme.background.source=card.dataset.source;theme.background.asset=null});status('已选择官方来源；请打开来源页下载并用本地导入应用图片。')}));
$('preset').addEventListener('click',()=>update(()=>{theme.accessibility.preset=theme.accessibility.preset==='high-read'?'workbench':'high-read';if(theme.accessibility.preset==='high-read'){theme.background.mode='solid';theme.background.asset=null;theme.background.taskIntensity=0;theme.background.dim=.94;theme.accessibility.reducedMotion=true}}));
$('export').addEventListener('click',()=>{const output=makeTheme(theme),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(output,null,2)],{type:'application/json'}));a.download='wukong-forge-theme.json';a.click();URL.revokeObjectURL(a.href);status('已导出可由运行时直接校验的主题配置。')});
render();
